---
- name: "Copy binary"
  ansible.builtin.copy:
    src: go-apt-mirror
    dest: "{{ go_apt_mirror_binary_path }}"
    owner: "{{ go_apt_mirror_user }}"
    group: "{{ go_apt_mirror_group }}"
    mode: '0755'

- name: "Copy configuration"
  ansible.builtin.copy:
    content: "{{ go_apt_mirror_config }}"
    dest: "{{ go_apt_mirror_config_path }}"
    owner: "{{ go_apt_mirror_user }}"
    group: "{{ go_apt_mirror_group }}"
    mode: '0644'

- name: "Create systemd"
  ansible.builtin.template:
    src: 'go-apt-mirror.service.j2'
    dest: '/etc/systemd/system/go-apt-mirror.service'
    mode: '0640'
  notify: "restart go-apt-mirror"

- name: "Enable and Start go-apt-mirror.service"
  ansible.builtin.service:
    name: go-apt-mirror
    state: started
    enabled: true
    daemon_reload: true
